### ISSUE TITLE
Negative viewport height validation error

### ISSUE THREAD

**Issue by JadTala** [travisvroman/kohi#11]
Using the Intel(R) Iris(TM) Graphics 550 iGPU on macOS, the following error shows up repeatedly:
`[ERROR]: Validation Error: [ VUID-VkViewport-height-01772 ] Object 0: handle = 0x7fa450cd8a88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa0dbe64d | vkCmdSetViewport: pViewports[0].height (=-600.000000) is not greater 0.0. The Vulkan spec states: height must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.2.148.0/mac/1.2-extensions/vkspec.html#VUID-VkViewport-height-01772)`

Making the viewport height positive in `vulkan_backend.c` solves the issue.

This doesn't happen with my AMD Radeon Pro 5500M dGPU on macOS, so this could be Intel specific.

**Comment by travisvroman** [comment]
This should be valid when targeting Vulkan 1.1+. Are you sure that's what is being targeted? If 1.0 is targeted, you may need to check for and use the `VK_KHR_Maintenance1` extension. I'm guessing this is a Mac-specific issue.

Note: making the viewport height positive _will_ break a great many things down the road otherwise.

I'll leave this open for now for responses.

**Comment by JadTala** [comment]
You're right, 1.0.148 is targeted, and I don't see any mention of the iGPU supporting more than 1.0 upon searching.

Since backward compatibility isn't the engine's focus for now, this can be closed.
